### ISSUE TITLE
[FEATURE] Add stop loss and take profit as general `backtest` parameters

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#185]
Currently, `backtest` does not allow users to specify the target profit / stop loss at which positions are exited. This can also be done at the strategy level, but I also realized (from feedback from one of our users) that this is a parameter that is likely generalizable across strategies.

**Comment by jpdeleon** [comment]
Related: https://www.backtrader.com/blog/posts/2018-02-01-stop-trading/stop-trading/

**Comment by enzoampil** [comment]
Will address the two sub-features below

- [ ] Stop loss
- [ ] Take profit

**Comment by enzoampil** [comment]
I will apply the two versions below, similar to the backtrader [sample]()

1. Either having a `Stop` fixed at a percentage below the acquisition price
2. Or setting a dynamic `StopTrail` which chases the price as it moves (using points in this case)

**Comment by zonemikel** [comment]
Hi, thanks for this feature, just adding I would like to see the take profit also. Not so worried about trailing but just having simple stop loss and take profit is pretty important. 

I did implement it myself in a custom strat, but for some strange reason it kept selling when it should not, even though in 'sell_signal' I never returned 'True' I would still get a sell, and even though I set allow_short=False I would still get a sell. So I'll wait for y'all to implement.

**Comment by enzoampil** [comment]
@zonemikel would you mind sharing your custom strat code? :smile:

**Comment by zonemikel** [comment]
I would not at all, I'll start it in a new issue so we don't pollute this one

**Comment by enzoampil** [comment]
Gotcha @zonemikel !

In the meantime, we can add in take profit support once bandwidth frees up, but if you'd like this faster, do feel free to try contributing it as well @zonemikel ! :smile:

I'd be happy to give you guidance on this. The implementation shouldn't be much different from the stop loss implementation (linked above), and the work will mostly be on the `BaseStrategy` module.

**Comment by enzoampil** [comment]
Both stop loss and take profit are now supported as per PR #377 .

Note that it's stable for both long only , and where allow_short = True, but we are yet to refine the experience when allowing for shorting. We recommend to mainly use this when doing long only (ie allow_short = False) for now!
